version: '3.1'

services:
  database:
    image: mariadb
    volumes:
      - data_sql:/var/lib/mysql
    networks:
      - ecoleta
    environment:
      MYSQL_DATABASE: ecoleta
      MYSQL_ROOT_PASSWORD: root
  
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    command: yarn workspace @ecoleta/api dev
    networks:
      - ecoleta
    ports:
      - 3333:3333
    volumes:
      - ./packages/api/src:/app/packages/api/src
      - ./packages/api/static:/app/packages/api/static
      - ./packages/api/package.json:/app/packages/api/package.json
      - ./packages/api/tsconfig.json:/app/packages/api/tsconfig.json
    env_file:
      - ./packages/api/.env

volumes:
  data_sql:
    driver: local

networks:
  ecoleta:
    driver: bridge
